#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagement1._0.Report
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLFinance")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::FinanceManagement1._0.Properties.Settings.Default.QLFinanceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FmIncome> FmIncomes
		{
			get
			{
				return this.GetTable<FmIncome>();
			}
		}
		
		public System.Data.Linq.Table<FmExpense> FmExpenses
		{
			get
			{
				return this.GetTable<FmExpense>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FmIncome")]
	public partial class FmIncome
	{
		
		private string _FmUser;
		
		private string _FmIncome1;
		
		private string _FmNote;
		
		private string _FmWName;
		
		private string _FmCatelogy;
		
		private string _FmCreatedDay;
		
		public FmIncome()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmUser", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmUser
		{
			get
			{
				return this._FmUser;
			}
			set
			{
				if ((this._FmUser != value))
				{
					this._FmUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FmIncome", Storage="_FmIncome1", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmIncome1
		{
			get
			{
				return this._FmIncome1;
			}
			set
			{
				if ((this._FmIncome1 != value))
				{
					this._FmIncome1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmNote", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmNote
		{
			get
			{
				return this._FmNote;
			}
			set
			{
				if ((this._FmNote != value))
				{
					this._FmNote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmWName", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmWName
		{
			get
			{
				return this._FmWName;
			}
			set
			{
				if ((this._FmWName != value))
				{
					this._FmWName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmCatelogy", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmCatelogy
		{
			get
			{
				return this._FmCatelogy;
			}
			set
			{
				if ((this._FmCatelogy != value))
				{
					this._FmCatelogy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmCreatedDay", DbType="NVarChar(52)")]
		public string FmCreatedDay
		{
			get
			{
				return this._FmCreatedDay;
			}
			set
			{
				if ((this._FmCreatedDay != value))
				{
					this._FmCreatedDay = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FmExpense")]
	public partial class FmExpense
	{
		
		private string _FmUser;
		
		private string _FmExpense1;
		
		private string _FmNote;
		
		private string _FmWName;
		
		private string _FmCreatedDate;
		
		private string _FmCatelogy;
		
		public FmExpense()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmUser", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmUser
		{
			get
			{
				return this._FmUser;
			}
			set
			{
				if ((this._FmUser != value))
				{
					this._FmUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FmExpense", Storage="_FmExpense1", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmExpense1
		{
			get
			{
				return this._FmExpense1;
			}
			set
			{
				if ((this._FmExpense1 != value))
				{
					this._FmExpense1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmNote", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmNote
		{
			get
			{
				return this._FmNote;
			}
			set
			{
				if ((this._FmNote != value))
				{
					this._FmNote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmWName", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmWName
		{
			get
			{
				return this._FmWName;
			}
			set
			{
				if ((this._FmWName != value))
				{
					this._FmWName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmCreatedDate", DbType="NVarChar(52) NOT NULL", CanBeNull=false)]
		public string FmCreatedDate
		{
			get
			{
				return this._FmCreatedDate;
			}
			set
			{
				if ((this._FmCreatedDate != value))
				{
					this._FmCreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FmCatelogy", DbType="NVarChar(52)")]
		public string FmCatelogy
		{
			get
			{
				return this._FmCatelogy;
			}
			set
			{
				if ((this._FmCatelogy != value))
				{
					this._FmCatelogy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
